language: scala

env:
  global:
    secure: "Cg5IC14UrPf4/PsGrjbvypjrkQqth5L9ANoM4DjY1fgpaaLDqo+GMyBFeBrQH0zY/jRL57ebtrdjaXeKrooCsx0yYQJnqcugHTW2XqIkUv48l1DQvTUasOpTVFjZbZnjMrpxjAWdAWLaKa+RZitVLgPeuJlAaKX9DyOEiyYDMD8="
scala:
  - 2.10.4
  - 2.11.4

sudo: false

script: "sbt clean coverage test"
after_success: "sbt coveralls"
